### ISSUE TITLE
Request edam to internal lookup

### ISSUE THREAD

**Issue by njall** [inkuzmin/edam-select#2]
Hi,

How difficult would it be to make a static function to query the internal ID by the EDAM term uri?
We are using edam-select, but we are storing the EDAM term URI rather than the internal ID. This is because we need to process the selected term and display it elsewhere; and this is being handled by an existing framework.
We could possible extend the table to store the internal ID too, but a getIdByTerm function would be great.

**Comment by inkuzmin** [comment]
Hi @njall!

Yes, that's a very good point. We can't expect developers to modify the application's model just for the sake of adding a UI component.

Internal IDs should be internal. I will check how to fix it with minimal performance loses and update it tomorrow.

**Comment by inkuzmin** [comment]
In addition to the API design issue you've pointed out, there is an argument that the building process as it is implemented presently provides no consistency guarantees – the internal IDs for the one version might not be matched with the same terms in the new one. To provide such guarantees would be much more difficult task than to update it to rely on EDAM IDs.

For the backward compatibility we might want to leave these methods, but hide them from the documentation (or mark as deprecated).

**Comment by njall** [comment]
Could a potential solution be to generate the internalIDs from edam terms? e.g. op1039, to0103, da0192 etc. That way the _preselect_ values could be inferred from terms; and the IDs would be consistent. Or is the implementation reliant on the internalids being generated as sequential integers?

**Comment by inkuzmin** [comment]
Interestingly, using integers wasn't actually a performance measure – we use them as keys in the hash, so it's O(1) in any case – but a way to reduce the file size. The thing is that each additional character (being repeated thousands times) adds up to the total library size which is too big for the utility UI component library already (~500KB).

I tested it, actually it's a matter of milliseconds to build another index for EDAM IDs. It looks like a reasonable solution. I am going to deploy the new version in a couple of hours.

API-wise, would it be convenient to use just EDAM URIs to communicate with the component, leaving internal IDs for component's internal needs?

Like
```
...
preselected: [
    "http://edamontology.org/topic_0091",
    ...
]
...
```

And
```
EdamSelect.getTermByUri("http://edamontology.org/topic_0091");
```

And in the `edam:change` callback in `event.detail`:
```
...
"edam_uri": "http://edamontology.org/topic_0091",
...
```

**Comment by njall** [comment]
Yep, that would be a very convenient solution for TeSS' needs :) Nice one :D

**Comment by inkuzmin** [comment]
@njall,
Done: https://www.npmjs.com/package/edam-select
Thank you for the insightful feedback!

**Comment by njall** [comment]
No, thank **you** for being an absolutely rockstar developer :D
